In [2]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier

C:\Users\Manzoo\Learning\LetsUpgrade-AI-ML\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [8]:
bank_loan_data=pd.read_excel("C:/Users/Manzoo/Learning/Day24/Assignment/Dataset/Bank_Personal_Loan_Modelling.xlsx",sheet_name=1)

bank_loan_data.isnull().sum()
bank_loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB

In [9]:
bank_loan_data.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [10]:
bank_loan_data.corr()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
ID,1.000000,-0.008473,-0.008326,-0.017695,0.013432,-0.016797,-0.024672,0.021463,-0.013920,-0.024801,-0.016972,-0.006909,-0.002528,0.017028
Age,-0.008473,1.000000,0.994215,-0.055269,-0.029216,-0.046418,-0.052030,0.041334,-0.012539,-0.007726,-0.000436,0.008043,0.013702,0.007681
Experience,-0.008326,0.994215,1.000000,-0.046574,-0.028626,-0.052563,-0.050089,0.013152,-0.010582,-0.007413,-0.001232,0.010353,0.013898,0.008967
Income,-0.017695,-0.055269,-0.046574,1.000000,-0.016410,-0.157501,0.645993,-0.187524,0.206806,0.502462,-0.002616,0.169738,0.014206,-0.002385
ZIP Code,0.013432,-0.029216,-0.028626,-0.016410,1.000000,0.011778,-0.004068,-0.017377,0.007383,0.000107,0.004704,0.019972,0.016990,0.007691
Family,-0.016797,-0.046418,-0.052563,-0.157501,0.011778,1.000000,-0.109285,0.064929,-0.020445,0.061367,0.019994,0.014110,0.010354,0.011588
CCAvg,-0.024672,-0.052030,-0.050089,0.645993,-0.004068,-0.109285,1.000000,-0.136138,0.109909,0.366891,0.015087,0.136537,-0.003620,-0.006686
Education,0.021463,0.041334,0.013152,-0.187524,-0.017377,0.064929,-0.136138,1.000000,-0.033327,0.136722,-0.010812,0.013934,-0.015004,-0.011014
Mortgage,-0.013920,-0.012539,-0.010582,0.206806,0.007383,-0.020445,0.109909,-0.033327,1.000000,0.142095,-0.005411,0.089311,-0.005995,-0.007231
Personal Loan,-0.024801,-0.007726,-0.007413,0.502462,0.000107,0.061367,0.366891,0.136722,0.142095,1.000000,0.021954,0.316355,0.006278,0.002802
Securities Account,-0.016972,-0.000436,-0.001232,-0.002616,0.004704,0.019994,0.015087,-0.010812,-0.005411,0.021954,1.000000,0.317034,0.012627,-0.015028
CD Account,-0.006909,0.008043,0.010353,0.169738,0.019972,0.014110,0.136537,0.013934,0.089311,0.316355,0.317034,1.000000,0.175880,0.278644
Online,-0.002528,0.013702,0.013898,0.014206,0.016990,0.010354,-0.003620,-0.015004,-0.005995,0.006278,0.012627,0.175880,1.000000,0.004210
CreditCard,0.017028,0.007681,0.008967,-0.002385,0.007691,0.011588,-0.006686,-0.011014,-0.007231,0.002802,-0.015028,0.278644,0.004210,1.000000

In [11]:
rf_bank_model=RandomForestClassifier(n_estimators=1000,max_features=2,oob_score=True)

In [12]:
bank_loan_data.columns

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [16]:
features=['Age','Experience','Income','Family','CCAvg','Education','Mortgage','Securities Account','CD Account','Online','CreditCard']

In [17]:
rf_bank_model.fit(X=bank_loan_data[features],y=bank_loan_data['Personal Loan'])

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=2,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [18]:
print(rf_bank_model.oob_score_)

0.988

In [20]:
for itr_features,imp in zip(features,rf_bank_model.feature_importances_):
    print(itr_features,imp)

Age 0.04464999975731306
Experience 0.044772002095669776
Income 0.3535460857508883
Family 0.09450925536964343
CCAvg 0.17667667607058554
Education 0.1619303610982312
Mortgage 0.04377928710717269
Securities Account 0.005750167690288349
CD Account 0.05594021946906124
Online 0.008496581691827668
CreditCard 0.00994936389931884

In [21]:
predictors=pd.DataFrame([bank_loan_data['Income'],bank_loan_data['CCAvg'],bank_loan_data['Education'],bank_loan_data['Family']]).T
print(predictors)

      Income  CCAvg  Education  Family
0       49.0    1.6        1.0     4.0
1       34.0    1.5        1.0     3.0
2       11.0    1.0        1.0     1.0
3      100.0    2.7        2.0     1.0
4       45.0    1.0        2.0     4.0
...      ...    ...        ...     ...
4995    40.0    1.9        3.0     1.0
4996    15.0    0.4        1.0     4.0
4997    24.0    0.3        3.0     2.0
4998    49.0    0.5        2.0     3.0
4999    83.0    0.8        1.0     3.0

[5000 rows x 4 columns]

In [28]:
tree_model=tree.DecisionTreeClassifier(max_depth=8)
tree_model.fit(X=predictors,y=bank_loan_data['Personal Loan'])
with open('Dtree_bankloan.dot','w') as f:
    f=tree.export_graphviz(tree_model,feature_names=['Income','CCAvg','Eductaion','Family'],out_file=f)

In [29]:
tree_model.score(X=predictors,y=bank_loan_data['Personal Loan'])

0.9956